[package]
name = "pdforganiser"
version = "0.1.0"
authors = ["vancha"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdk = "0.13.2"
gio = "0.9.1"
gtk = "0.9.2"
libhandy = "0.7.1"

